name: Submit new Provider
description: Submit a new OpenTofu Provider
title: "Provider: "
labels: ["provider", "submission"]
body:
  - type: input
    id: repository
    attributes:
      label: Repository
      description: Path to a public GitHub repository following the pattern {owner}/terraform-provider-{name}, ex. opentofu/terraform-provider-aws
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: DCO
      options:
        - label: I sign this project's [DCO](https://developercertificate.org/)
          required: true
