name: Bump Provider and Module Versions

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The environment of the Registry
        options:
          - Development
          - Production
  workflow_call:
    inputs:
      environment:
        type: string
        description: The environment of the Registry

jobs:
  bump-versions:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
    permissions:
      contents: write
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        prefix: ["0", "1", "2", "3", "4", "5", "6", "7", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './src/go.mod'
          cache-dependency-path: './src/go.sum'
      - name: Bump Versions
        run: ./.github/workflows/bump-versions.sh
        env:
          PREFIX: ${{ matrix.prefix }}
          ENVIRONMENT: ${{ inputs.environment }}
