name: Provider Labeled
on:
  issues:
    types:
      [opened, edited]

jobs:
  label_issues:
    if: contains(github.event.issue.labels.*.name, 'provider')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Provider Issue to Pull Request
        run: |
          # Pull provider out of issue body
          provider=`$(echo "$BODY" | grep "### Repository" -A2 | tail -n1)`
          echo "Detected Provider '$provider'"

          # Check that provider matches expected pattern
          if [[ "$provider" =~ [a-zA-Z0-9\-]+/terraform-provider-[a-zA-Z0-9\-]+ ]]; then
            gh issue comment $NUMBER -b "Failed validation: Invalid provider '$provider'"
            exit 1
          fi

          # Split provider into namespace/terraform-provider-name
          namespace=${provider/\/*/}
          name=${provider/*\/terraform-provider-/}
          echo "Detected Namespace '$namespace'"
          echo "Detected Name '$name'"

          jsonfile=$(echo "$namespace/$name" | sed -e 's,\(.\)\(.*\)/\(.*\),./providers/\L\1\E/\1\2/\3.json,')

          if [[ -f $jsonfile ]]; then
            gh issue comment $NUMBER -b "Failed validation: This provider already exists within the registry. $jsonfile"
            exit 1
          fi

          mkdir -p $(dirname $jsonfile)
          echo '{}' > $jsonfile


          git config --global user.email "no-reply@opentofu.org"
          git config --global user.name "OpenTOFU Automation"

          branch="provider-submission_$namespace_$name"
          set +e
          git checkout -b $branch
          if [[ "$?" != 0 ]]; then
            gh issue comment $NUMBER -b "Failed validation: A branch already exists for this provider '$branch'"
            exit 1
          fi
          set -e

          git add $jsonfile
          git commit -s -m "Create provider $namespace/$name"
          git push -u origin provider-submission_$namespace_$name

          pr=$(gh pr create --title "$TITLE" --body "Created $jsonfile for provider $namespace/$name.  See issue #$NUMBER for details.") #--assignee opentofu/core-engineers)

          gh issue comment $NUMBER -b "Your submission has been accepted and has moved on to the pull request phase ($pr)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          URL: ${{ github.event.issue.url }}
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
