name: Provider Labeled
on:
  issues:
    types: [labeled]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Added Label to $NUMBER: $LABEL"
        env:
          NUMBER: ${{ github.event.issue }}
          LABEL: ${{ github.event.label.name }}
